[package]
name = "visit"
version = "0.3.1"
authors = ["Kyle Partridge <kyle.partridge@sendgrid.com>"]

[dependencies]
redis = "*"
hyper = "0.11"
futures = "*"
hostname = "^0.1"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
